services:
  - type: web
    name: catalyst-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: PORT
        value: 5000
    repo: https://github.com/Saurabh-Jasawat/Catalyst.git
    branch: develop
